### ISSUE TITLE
Typescript Compiler Error in d.ts - Module '"electron"' has no exported member 'AllElectron'

### ISSUE THREAD

**Issue by warrenbuckley** [sindresorhus/electron-util#38] opened 2020-12-23 16:25 UTC
Error when using Typescript
`node_modules/electron-util/index.d.ts:4:9 - error TS2305: Module '"electron"' has no exported member 'AllElectron'.`

## Error from TypeScript CLI
![image](https://user-images.githubusercontent.com/1389894/103016840-a09d1180-453a-11eb-9de3-cec5b8e3c552.png)

## Versions
Typescript Version: 4.1.3
Node Version: v14.15.1
Windows: 10.0.19042 Build 19042

## TSConfig
```json
{
  "compilerOptions": {
      "module": "commonjs",
      "esModuleInterop": true,
      "target": "es6",
      "noImplicitAny": false,
      "moduleResolution": "node",
      "sourceMap": true,
      "strictNullChecks": false,
      "outDir": "dist",
      "baseUrl": ".",
      "paths": {
          "*": [
              "node_modules/*",
              "src/types/*"
          ]
      },
      "plugins": [],
  },
  "include": [
      "src/**/*"
  ]
}
```

## Package.json
```json
{
  "name": "logviewer.client",
  "productName": "Compact Log Viewer",
  "version": "1.0.6",
  "description": "A cross platform Electron app to view and search logs stored in the Compact log format",
  "homepage": "https://github.com/warrenbuckley/Compact-Log-Format-Viewer#readme",
  "repository": {
    "type": "git",
    "url": "https://github.com/warrenbuckley/Compact-Log-Format-Viewer.git"
  },
  "main": "dist/main/main.js",
  "scripts": {
    "start": "electron .",
    "lint": "eslint -c .eslintrc.js --ext .ts src",
    "tsc": "tsc --diagnostics",
    "watch": "tsc --watch",
    "win": "electron-builder --publish never --win --config ./electron-builder.json",
    "mac": "electron-builder --publish never --mac --config electron-builder.json"
  },
  "author": "Warren Buckley",
  "license": "ISC",
  "private": true,
  "devDependencies": {
    "@types/angular": "^1.8.0",
    "@types/chart.js": "^2.9.29",
    "@types/electron-is-dev": "^1.1.1",
    "@types/request": "^2.48.5",
    "@typescript-eslint/eslint-plugin": "^4.10.0",
    "@typescript-eslint/parser": "^4.10.0",
    "electron": "^11.1.0",
    "electron-builder": "^22.9.1",
    "eslint": "^7.16.0",
    "eslint-plugin-jsdoc": "^30.7.8",
    "eslint-plugin-prefer-arrow": "^1.2.2",
    "tslint": "^6.1.3",
    "typescript": "^4.1.3",
    "typescript-tslint-plugin": "^1.0.1"
  },
  "dependencies": {
    "angular": "^1.8.2",
    "angular-chart.js": "^1.1.1",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "electron-log": "^4.3.1",
    "electron-util": "^0.14.2",
    "jquery": "^3.5.1",
    "popper.js": "^1.16.1",
    "request": "^2.88.2"
  }
}
```

**Comment by sindresorhus** [comment] 2020-12-24 08:29
Duplicate of https://github.com/sindresorhus/electron-util/issues/36

**Closed by sindresorhus** 2020-12-24 08:29 UTC
