### ISSUE TITLE
It seems that not work on >= v14 electron's version

### ISSUE THREAD

**Issue by curiduck** [sindresorhus/electron-util#57] opened 2022-05-02 08:46 UTC
Hi, I use this library on Electron v18.
It not work because 'electron-is-dev' version is low, it is not compatible with this version.

![image](https://user-images.githubusercontent.com/71216905/166209110-a0a4b701-3e5f-4152-b807-2f8fd0b4ff06.png)

electron.remote was deprecated on Electron v14.

I think this issue will resolved if upgrade 'electron-is-dev' version to v2.0.0.

Has any way to solve or avoid this issue?

**Comment by sindresorhus** [comment] 2022-05-02 12:25
Duplicate of #45

**Closed by sindresorhus** 2022-05-02 12:25 UTC
